using Microsoft.Data.SqlClient;
namespace GBManufacturingTracker;
public partial class CheckoutForm:Form
{ public CheckoutForm(){InitializeComponent();LoadCombos();LoadTransactions();}
  private void LoadCombos(){cboUser.DataSource=Db.GetTable("SELECT UserID, FullName FROM Users ORDER BY FullName");cboUser.DisplayMember="FullName";cboUser.ValueMember="UserID";cboEquipment.DataSource=Db.GetTable("SELECT EquipmentID, EquipmentName FROM Equipment WHERE Status IN ('Available','Checked Out') ORDER BY EquipmentName");cboEquipment.DisplayMember="EquipmentName";cboEquipment.ValueMember="EquipmentID";}
  private void LoadTransactions(){dgvTransactions.DataSource=Db.GetTable(@"SELECT t.TransactionID,u.FullName,e.EquipmentName,t.CheckoutDate,t.DueDate,t.ReturnDate,t.TransactionStatus FROM CheckoutTransactions t JOIN Users u ON t.UserID=u.UserID JOIN Equipment e ON t.EquipmentID=e.EquipmentID ORDER BY t.TransactionID DESC");}
  private void btnCheckout_Click(object? s,EventArgs e){Db.Execute(@"INSERT INTO CheckoutTransactions(UserID,EquipmentID,CheckoutDate,DueDate,TransactionStatus) VALUES(@u,@eq,@c,@d,'Checked Out'); UPDATE Equipment SET Status='Checked Out' WHERE EquipmentID=@eq",new SqlParameter("@u",cboUser.SelectedValue),new SqlParameter("@eq",cboEquipment.SelectedValue),new SqlParameter("@c",dtCheckout.Value),new SqlParameter("@d",dtDue.Value));LoadCombos();LoadTransactions();}
  private void btnReturn_Click(object? s,EventArgs e){if(txtTransactionId.Text=="")return;Db.Execute(@"UPDATE CheckoutTransactions SET ReturnDate=GETDATE(), TransactionStatus='Returned' WHERE TransactionID=@id; UPDATE Equipment SET Status=CASE WHEN @damaged=1 THEN 'Damaged' ELSE 'Available' END WHERE EquipmentID=(SELECT EquipmentID FROM CheckoutTransactions WHERE TransactionID=@id)",new SqlParameter("@id",txtTransactionId.Text),new SqlParameter("@damaged",chkDamaged.Checked)); if(chkDamaged.Checked){ using DamageReportForm f=new(txtTransactionId.Text); f.ShowDialog(); }LoadCombos();LoadTransactions();}
  private void dgvTransactions_CellClick(object? s,DataGridViewCellEventArgs e){if(e.RowIndex>=0)txtTransactionId.Text=dgvTransactions.Rows[e.RowIndex].Cells["TransactionID"].Value?.ToString();}
  private void btnClose_Click(object? s,EventArgs e)=>Close(); }
