using Microsoft.Data.SqlClient;
namespace GBManufacturingTracker;
public partial class DamageReportForm:Form
{ public DamageReportForm(){InitializeComponent();LoadEquipment();LoadReports();} public DamageReportForm(string transactionId):this(){txtTransactionId.Text=transactionId;}
  private void LoadEquipment(){cboEquipment.DataSource=Db.GetTable("SELECT EquipmentID, EquipmentName FROM Equipment ORDER BY EquipmentName");cboEquipment.DisplayMember="EquipmentName";cboEquipment.ValueMember="EquipmentID";}
  private void LoadReports(){dgvReports.DataSource=Db.GetTable(@"SELECT d.DamageReportID,e.EquipmentName,d.TransactionID,d.DamageDate,d.Severity,d.Description,d.ActionTaken,d.ReportSavedPath FROM DamageReports d JOIN Equipment e ON d.EquipmentID=e.EquipmentID ORDER BY d.DamageReportID DESC");}
  private void btnSave_Click(object? s,EventArgs e){Db.Execute(@"INSERT INTO DamageReports(EquipmentID,TransactionID,ReportedByUserID,DamageDate,Severity,Description,ActionTaken) VALUES(@eq,NULLIF(@tid,''),@u,@date,@sev,@desc,@action)",new SqlParameter("@eq",cboEquipment.SelectedValue),new SqlParameter("@tid",txtTransactionId.Text),new SqlParameter("@u",Session.UserId==0?1:Session.UserId),new SqlParameter("@date",dtDamage.Value),new SqlParameter("@sev",cboSeverity.Text),new SqlParameter("@desc",txtDescription.Text),new SqlParameter("@action",txtAction.Text));Db.Execute("UPDATE Equipment SET Status='Damaged' WHERE EquipmentID=@eq",new SqlParameter("@eq",cboEquipment.SelectedValue));LoadReports();MessageBox.Show("Damage report saved to database.");}
  private void btnExport_Click(object? s,EventArgs e){ if(dgvReports.CurrentRow==null)return; int id=Convert.ToInt32(dgvReports.CurrentRow.Cells["DamageReportID"].Value); string file=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),$"DamageReport_{id}.txt"); File.WriteAllText(file,$"GB Manufacturing Damage Report #{id}\r\nEquipment: {dgvReports.CurrentRow.Cells["EquipmentName"].Value}\r\nDate: {dgvReports.CurrentRow.Cells["DamageDate"].Value}\r\nSeverity: {dgvReports.CurrentRow.Cells["Severity"].Value}\r\nDescription: {dgvReports.CurrentRow.Cells["Description"].Value}\r\nAction Taken: {dgvReports.CurrentRow.Cells["ActionTaken"].Value}"); Db.Execute("UPDATE DamageReports SET ReportSavedPath=@p WHERE DamageReportID=@id",new SqlParameter("@p",file),new SqlParameter("@id",id));LoadReports();MessageBox.Show("Report exported to: "+file);}
  private void btnClear_Click(object? s,EventArgs e){txtTransactionId.Clear();txtDescription.Clear();txtAction.Clear();cboSeverity.SelectedIndex=0;} private void btnClose_Click(object? s,EventArgs e)=>Close();}
