IF DB_ID('GBManufacturingTrackerDB') IS NULL
    CREATE DATABASE GBManufacturingTrackerDB;
GO
USE GBManufacturingTrackerDB;
GO

IF OBJECT_ID('DamageReports','U') IS NOT NULL DROP TABLE DamageReports;
IF OBJECT_ID('CheckoutTransactions','U') IS NOT NULL DROP TABLE CheckoutTransactions;
IF OBJECT_ID('Equipment','U') IS NOT NULL DROP TABLE Equipment;
IF OBJECT_ID('Users','U') IS NOT NULL DROP TABLE Users;
IF OBJECT_ID('Roles','U') IS NOT NULL DROP TABLE Roles;
GO

CREATE TABLE Roles(
    RoleID INT IDENTITY(1,1) PRIMARY KEY,
    RoleName NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Users(
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(200) NOT NULL,
    FullName NVARCHAR(100) NOT NULL,
    RoleID INT NOT NULL FOREIGN KEY REFERENCES Roles(RoleID),
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE Equipment(
    EquipmentID INT IDENTITY(1,1) PRIMARY KEY,
    Barcode NVARCHAR(75) NULL UNIQUE,
    EquipmentName NVARCHAR(100) NOT NULL,
    Category NVARCHAR(75) NULL,
    SerialNumber NVARCHAR(75) NULL,
    WarehouseLocation NVARCHAR(100) NULL,
    Status NVARCHAR(25) NOT NULL DEFAULT 'Available',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE CheckoutTransactions(
    TransactionID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID),
    EquipmentID INT NOT NULL FOREIGN KEY REFERENCES Equipment(EquipmentID),
    CheckoutDate DATETIME2 NOT NULL,
    DueDate DATETIME2 NOT NULL,
    ReturnDate DATETIME2 NULL,
    TransactionStatus NVARCHAR(25) NOT NULL
);

CREATE TABLE DamageReports(
    DamageReportID INT IDENTITY(1,1) PRIMARY KEY,
    EquipmentID INT NOT NULL FOREIGN KEY REFERENCES Equipment(EquipmentID),
    TransactionID INT NULL FOREIGN KEY REFERENCES CheckoutTransactions(TransactionID),
    ReportedByUserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID),
    DamageDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    Severity NVARCHAR(25) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    ActionTaken NVARCHAR(MAX) NULL,
    ReportSavedPath NVARCHAR(500) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO

INSERT INTO Roles(RoleName) VALUES ('Admin'),('Supervisor'),('Employee');

-- Default login requested by user: admin / 1976
-- Hash generated by BCrypt.Net-Next for password 1976.
INSERT INTO Users(Username, PasswordHash, FullName, RoleID)
VALUES ('admin', '$2a$11$OYnShDuiX6i8TXU4BCkL6ucgXQmKCkUDs5xbNSOgX5oTIp1q7VH8e', 'System Administrator', 1);

INSERT INTO Equipment(Barcode, EquipmentName, Category, SerialNumber, WarehouseLocation, Status) VALUES
('BC-1001','Cordless Drill','Power Tool','DR-1001','Warehouse A','Available'),
('BC-1002','Impact Wrench','Power Tool','IW-3002','Warehouse A','Available'),
('BC-1003','Ladder 12 ft','Safety','LD-1200','Warehouse B','Available'),
('BC-1004','Tool Box Set','Hand Tools','TB-7788','Warehouse B','Available');
GO
